packages:
  - packages/*
  - apps/*

catalog:
  '@nuxt/ui': ^4.1.0
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/vue-query': ^5.90.2
  '@types/node': ^24.10.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/tsconfig': ^0.8.1
  dayjs: ^1.11.19
  drizzle-orm: ^0.44.5
  drizzle-zod: ^0.8.3
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  rollup-plugin-visualizer: ^6.0.5
  tailwindcss: ^4.1.17
  typescript: ~5.9.3
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-router: ^0.16.1
  vite: ^7.2.2
  vite-plugin-vue-devtools: ^8.0.3
  vue: ^3.5.23
  vue-router: ^4.6.3
  vue-tsc: ^3.1.3
